server:
  interface: ""  # 留空让系统自动选择接口
  server_ip: "192.168.1.88"
  subnet_mask: "255.255.255.0"
  broadcast_address: "192.168.1.255"

dhcp:
  pool_start: "192.168.1.100"
  pool_end: "192.168.1.222"
  lease_time: 3600

options:
  router: "192.168.1.1"
  dns_servers:
    - "8.8.8.8"
    - "8.8.4.4"
  domain_name: "local"
  next_server: "192.168.1.88"
  filename: "undionly.kpxe"
  additional_options:
    - code: 66  # TFTP服务器名称
      value: "192.168.1.88"
    - code: 67  # 引导文件名
      value: "undionly.kpxe"
    - code: 150 # TFTP服务器地址
      value: "192.168.1.88"

pxe:
  enabled: true
  tftp_server: "192.168.1.88"
  default_boot_filename: "snponly.efi"
  architecture_specific:
    - arch: 0  # BIOS
      boot_filename: "undionly.kpxe"    # 传统BIOS使用
    - arch: 7  # UEFI x64
      boot_filename: "snponly.efi"      # UEFI系统使用
  ipxe:
    enabled: true
    http_server: "http://192.168.1.88:8080/pxe"
    boot_script: "boot.ipxe"

tftp:
  root_dir: "./bootfile"
  bind_address: "0.0.0.0"
  port: 69
  status_check_interval: 5
  startup_timeout: 30
  block_size: 512
  timeout: 5
  retries: 5
  log_level: "DEBUG"