server:
  interface: ""  # 留空让系统自动选择接口
  server_ip: "192.168.1.88"
  subnet_mask: "255.255.255.0"
  broadcast_address: "192.168.1.255"

dhcp:
  pool_start: "192.168.1.100"
  pool_end: "192.168.1.222"
  lease_time: 3600

options:
  router: "192.168.1.1"
  dns_servers:
    - "8.8.8.8"
    - "8.8.4.4"
  domain_name: "local"

pxe:
  enabled: true
  tftp_server: "192.168.1.88"
  default_boot_filename: "undionly.kpxe"
  architecture_specific:
    - arch: 0  # BIOS
      boot_filename: "undionly.kpxe"
    - arch: 7  # UEFI x64
      boot_filename: "snponly.efi"
    - arch: 9  # UEFI x86
      boot_filename: "ipxe.efi"
  ipxe:
    enabled: true
    http_server: "http://192.168.1.1:8080"  # iPXE脚本HTTP服务器
    boot_script: "boot.ipxe"  # iPXE引导脚本名称












# 在现有配置文件中添加TFTP服务器配置
tftp:
  root_dir: "./bootfile"  # TFTP文件根目录
  bind_ip: "0.0.0.0"      # 监听地址
  port: 69                # TFTP端口
  block_size: 512         # 数据块大小
  timeout: 5              # 超时时间（秒）
  retries: 5              # 重试次数