server:
  interface: ""  # 留空让系统自动选择接口
  server_ip: "192.168.1.88"
  subnet_mask: "255.255.255.0"
  broadcast_address: "192.168.1.255"

dhcp:
  pool_start: "192.168.1.100"
  pool_end: "192.168.1.222"
  lease_time: 3600

options:
  router: "192.168.1.1"
  dns_servers:
    - "8.8.8.8"
    - "8.8.4.4"
  domain_name: "local"
  next_server: "192.168.1.88"  # 添加next-server选项
  vendor_specific_information: ""  # 添加vendor特定信息

pxe:
  enabled: true
  tftp_server: "192.168.1.88"
  default_boot_filename: "snponly.efi"
  architecture_specific:
    - arch: 0  # BIOS
      boot_filename: "undionly.kpxe"
    - arch: 6  # EFI IA32
      boot_filename: "ipxe-ia32.efi"
    - arch: 7  # UEFI x64
      boot_filename: "snponly.efi"
    - arch: 9  # EFI x86
      boot_filename: "ipxe.efi"
  ipxe:
    enabled: true
    http_server: "http://192.168.1.88:8080"  # 修改为与TFTP服务器相同的IP
    boot_script: "boot.ipxe"

tftp:
  root_dir: "./bootfile"
  bind_address: "0.0.0.0"
  port: 69
  status_check_interval: 5    # 状态检查间隔（秒）
  startup_timeout: 30         # 启动超时时间（秒）
  block_size: 512            # 数据块大小
  retries: 5                 # 重试次数